# 宣告 Prometheus Operator 的 ServiceMonitor 自訂資源定義 (Custom Resource Definition, CRD)
# 供 monitoring 命名空間中的 Prometheus 自動探索並採集 Spring Boot Actuator 指標
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-servicemonitor
  labels:
    app: {{ .Release.Name }}
    release: prometheus-stack # 關聯至 kube-prometheus-stack Release
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
